name: Flutter Web
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web

    runs-on: ubuntu-latest

    env:
        working-directory: ./toonflix

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ${{ env.working-directory }}/pubspec.yaml

      - name: Build Flutter Web
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release --base-href /practice-flutter/
        working-directory: ${{ env.working-directory }}

      - name: Deploy to GitHub Pages
        run: |
          git init
          git config --global user.email topkim.dev@gmail.com
          git config --global user.name topkim993
          git status
          git remote add origin https://${{secrets.ACTION_TOKEN}}@github.com/topkim993/practice-flutter.git
          git checkout -b gh-pages
          git add --all
          git commit -m "build: Deploy to GitHub Pages"
          git push origin gh-pages -f
        working-directory: ${{ env.working-directory }}/build/web